// Mock data for the Pallet platform

export const products = [
  {
    id: "paneer-1kg",
    name: "Fresh Paneer",
    sku: "PNR-001",
    unit: "Case (4x 1kg)",
    price: 85.0,
    pricing: {
      gold: 81.0,
      silver: 83.0,
      standard: 85.0,
    },
    stock: 150,
    status: "in_stock",
    category: "Dairy",
  },
  {
    id: "samosa-12pcs",
    name: "Vegetable Samosa",
    sku: "SAM-001",
    unit: "Case (12 pcs)",
    price: 32.0,
    pricing: {
      gold: 30.4,
      silver: 31.2,
      standard: 32.0,
    },
    stock: 45,
    status: "low_stock",
    category: "Snacks",
  },
  {
    id: "biryani-rice-5kg",
    name: "Basmati Biryani Rice",
    sku: "BIR-001",
    unit: "Bag (5kg)",
    price: 45.0,
    pricing: {
      gold: 42.75,
      silver: 43.88,
      standard: 45.0,
    },
    stock: 200,
    status: "in_stock",
    category: "Grains",
  },
  {
    id: "naan-12pcs",
    name: "Tandoori Naan",
    sku: "NAN-001",
    unit: "Case (12 pcs)",
    price: 28.0,
    pricing: {
      gold: 26.6,
      silver: 27.3,
      standard: 28.0,
    },
    stock: 0,
    status: "out_of_stock",
    category: "Breads",
  },
  {
    id: "chai-mix-500g",
    name: "Masala Chai Mix",
    sku: "CHA-001",
    unit: "Box (500g)",
    price: 18.5,
    pricing: {
      gold: 17.58,
      silver: 18.04,
      standard: 18.5,
    },
    stock: 120,
    status: "in_stock",
    category: "Beverages",
  },
  {
    id: "mango-lassi-1l",
    name: "Mango Lassi Base",
    sku: "LAS-001",
    unit: "Carton (1L)",
    price: 12.0,
    pricing: {
      gold: 11.4,
      silver: 11.7,
      standard: 12.0,
    },
    stock: 80,
    status: "in_stock",
    category: "Beverages",
  },
]

export const stores = [
  {
    id: "store-1",
    name: "Delhi Market - Toronto",
    email: "demo@retailer.com",
    type: "Grocery Store",
    city: "Toronto",
    tier: "gold",
    status: "active",
    creditLimit: 50000,
    creditUsed: 12350,
    accountManager: "Raj Kumar",
  },
  {
    id: "store-2",
    name: "Spice Route Restaurant",
    email: "contact@spiceroute.com",
    type: "Restaurant",
    city: "Vancouver",
    tier: "silver",
    status: "active",
    creditLimit: 35000,
    creditUsed: 8920,
    accountManager: "Priya Sharma",
  },
  {
    id: "store-3",
    name: "Punjab Express",
    email: "info@punjabexpress.com",
    type: "Distributor",
    city: "Calgary",
    tier: "standard",
    status: "pending",
    creditLimit: 20000,
    creditUsed: 0,
    accountManager: "Unassigned",
  },
]

export const orders = [
  {
    id: "ORD-001",
    storeId: "store-1",
    storeName: "Delhi Market - Toronto",
    date: "2025-01-28",
    status: "delivered",
    total: 2450.5,
    items: [
      { productId: "paneer-1kg", quantity: 10, price: 85.0 },
      { productId: "samosa-12pcs", quantity: 5, price: 30.4 },
    ],
  },
  {
    id: "ORD-002",
    storeId: "store-1",
    storeName: "Delhi Market - Toronto",
    date: "2025-01-26",
    status: "out_for_delivery",
    total: 1680.0,
    items: [{ productId: "biryani-rice-5kg", quantity: 8, price: 42.75 }],
  },
  {
    id: "ORD-003",
    storeId: "store-2",
    storeName: "Spice Route Restaurant",
    date: "2025-01-25",
    status: "processing",
    total: 892.5,
    items: [
      { productId: "chai-mix-500g", quantity: 15, price: 17.58 },
      { productId: "mango-lassi-1l", quantity: 10, price: 11.4 },
    ],
  },
]

export const invoices = [
  {
    id: "INV-001",
    orderId: "ORD-001",
    date: "2025-01-28",
    amount: 2450.5,
    status: "paid",
  },
  {
    id: "INV-002",
    orderId: "ORD-002",
    date: "2025-01-26",
    amount: 1680.0,
    status: "paid",
  },
]
